### ISSUE TITLE
[Store.get_store_id] its return value may be collision

### ISSUE THREAD

**Issue by kichinosukey** [beyond-blockchain/bbc1-lib-tokens#12]
"get_store_id" generates bytes class object in it and the object uses mint_id. But the object is not contained to return value. In this case, this function seems to return only two values. If this issue has some problems, I will improve this part and send pull-request.

Thanks,

https://github.com/beyond-blockchain/bbc1-lib-tokens/blob/5e7c48ed68ae122ee44ba795b647545aa506d892/bbc1/lib/token_lib.py#L708

**Comment by ks91** [comment]
Thank you for raising an issue. store_id is a special key in the mint storage with which one can search the condition or the currency spec of the mint. get_store_id is designed to return a digest generated from the mint_id and a seed (that differs between the condition and the currency spec). The returned value, I think, is unlikely to collide with others.

**Comment by kichinosukey** [comment]
But returned value seems not to contain the mint_id or its seed like below. If my understanding is poor for this code line behavior, I'm so sorry.

I tested below and original code got assertion error. And revised one got no error. Is my test point wrong? Could you hear me your idea?

```
import hashlib
from bbc1.core import bbclib

SEED = '.seed'

mint_id_1 = bbclib.get_new_id('test_mint_1')
mint_id_2 = bbclib.get_new_id('test_mint_2')

def get_store_id(id_digest):
    dat = bytearray(id_digest)
    dat.extend(SEED.encode())
    return hashlib.sha256(bytes()).digest()

def get_store_id_rev(id_digest):
    dat = bytearray(id_digest)
    dat.extend(SEED.encode())
    return hashlib.sha256(bytes(dat)).digest

def test_get_store_id():
    assert get_store_id_rev(mint_id_1) != get_store_id_rev(mint_id_2)

if __name__ == '__main__':

    test_get_store_id()
```

**Comment by ks91** [comment]
I am terribly sorry. Now I know what you mean!
Thank you very much for pointing the problem out.
I have made corrections to the library and its test code.

**Comment by kichinosukey** [comment]
I'm sorry too. I couldn't explain what I want to say.

And thank you so much!!
